namespace FlowGraph.Core.Models;

/// <summary>
/// Determines how an edge's path is calculated.
/// </summary>
public enum EdgeRoutingMode
{
    /// <summary>
    /// Path is fully calculated by the router (default behavior).
    /// Waypoints in EdgeState are auto-generated by the routing algorithm.
    /// </summary>
    Auto,

    /// <summary>
    /// Path uses only user-defined waypoints.
    /// Auto-routing is disabled; the edge passes directly through UserWaypoints.
    /// </summary>
    Manual,

    /// <summary>
    /// Router calculates path but respects user waypoints as constraints.
    /// The path will pass through UserWaypoints while avoiding obstacles.
    /// Combines manual control with automatic obstacle avoidance.
    /// </summary>
    Guided
}
